### ISSUE TITLE
Crash during upload

### ISSUE THREAD

**Issue by Cralex** [Kyraminol/3DSync#3]
Hello, I'm using the current .cia release on a N2DSXL running 11.12.0-45. It definitely uploaded some saves, but eventually it crashed. I tried again and the same thing happened. Here's the crash log from the most recent crash: 
[crash_dump_00000001.dmp.zip](https://github.com/Kyraminol/3DSync/files/4468226/crash_dump_00000001.dmp.zip)
By the way, I'm running Luma 10.0.1 and Fastboot3ds. Thanks!

**Comment by Kyraminol** [comment]
It should be resolved on latest release, update and check :)

**Comment by Cralex** [comment]
It’s definitely better, yes. Once I figured out the new version needs a new config file, I was able to consistently run it without further crashes. However, it seems to eventually stop on one file or another before it would normally write the line with the Curl result. It doesn’t seem to be consistent where it stops. Turning off wireless (using Luma’s Rosalina feature) while it’s stuck will cause a long string of “couldn’t resolve host name” errors, and turning wireless back on will restart the upload wherever it’s at when the system reconnects.

**Comment by Kyraminol** [comment]
Try this debug version, it is the same but has a more verbose output. Try to figure out where it stops.
Try moving the 3DS closer to the wifi source and remove any custom DNS, it may be slowing down the already slow 3DS wifi

[3DSync.zip](https://github.com/Kyraminol/3DSync/files/4665477/3DSync.zip)

**Comment by Cralex** [comment]
It might be my wifi after all. I tried with the debug version on my home wifi, which is actually from AT&T over LTE, and it froze up twice as previously described. (Again, I toggled wifi to restart the upload job.) I am attaching screenshots of my home wifi run below.

![636B6AE6-1611-4723-8476-607C86C386BE](https://user-images.githubusercontent.com/1504649/82627878-a992c280-9ba8-11ea-93c0-3196aa583ab1.jpeg)
![8C726CF3-1612-4715-BC4F-8303B2616229](https://user-images.githubusercontent.com/1504649/82627893-ae577680-9ba8-11ea-9f8c-4260b331ad52.jpeg)

I then tethered my 3DS to my phone, which is getting internet through Metro by T-Mobile. The upload job to Dropbox finished without errors.

**Comment by Kyraminol** [comment]
I removed the comment because screenshots were sporting your token and anyone could have used them to gain access to your files

Anyway I'll close this for the moment because it appears to be a slow/stuttering network on an already slow 3DS WiFi (HTTPS with TLS1.2 is like 150kbps).

I'll try to make an "quit uploading this file and retry" button so if it stops for whatever reason you can retry that file
